# Generated by Django 5.2.1 on 2025-05-21 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100, unique=True)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=254, unique=True)),
                ('staff_phone', models.CharField(max_length=15)),
                ('staff_department', models.CharField(max_length=100)),
                ('staff_position', models.CharField(max_length=100)),
                ('staff_joining_date', models.DateField()),
                ('staff_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('leave_reason', models.TextField()),
                ('leave_status', models.CharField(default='Pending', max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hr.staff', to_field='staff_id')),
            ],
        ),
    ]
